# Generated by Django 3.0.8 on 2020-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201101_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='val_neg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='val_pos',
            field=models.IntegerField(default=0),
        ),
    ]
