# Generated by Django 3.1.3 on 2020-11-13 17:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201113_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[core.validators.validate_email]),
        ),
    ]
