# Generated by Django 3.0.8 on 2020-11-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classi',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('classi', models.ManyToManyField(to='content.Classe')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materie',
            },
        ),
        migrations.CreateModel(
            name='Professore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cognome', models.CharField(max_length=60)),
                ('classi', models.ManyToManyField(blank=True, related_name='profs', to='content.Classe')),
                ('materie', models.ManyToManyField(to='content.Materia')),
            ],
            options={
                'verbose_name': 'Professore',
                'verbose_name_plural': 'Professori',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=60)),
                ('immagine', models.ImageField(upload_to='')),
                ('file_pdf', models.FileField(blank=True, upload_to='pdf')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Classe')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Materia')),
                ('professore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Professore')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Note',
            },
        ),
    ]
