# Generated by Django 3.0.8 on 2020-11-02 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_nota_studente'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data_pubblicazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='immagine',
            field=models.ImageField(upload_to='notes/'),
        ),
    ]
