# Generated by Django 3.0.8 on 2020-11-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201102_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='non_utile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nota',
            name='utile',
            field=models.IntegerField(default=0),
        ),
    ]
