# Generated by Django 3.0.8 on 2020-11-02 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_auto_20201102_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='votanti',
            field=models.ManyToManyField(blank=True, related_name='note_votate', to=settings.AUTH_USER_MODEL),
        ),
    ]
