# Generated by Django 3.0.8 on 2020-11-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0006_nota_votanti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Nota')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'segnalazione',
                'verbose_name_plural': 'segnalazioni',
            },
        ),
    ]
