# Generated by Django 3.0.8 on 2020-11-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_segnalazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='messaggio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='motivo',
            field=models.CharField(choices=[('Linguaggio Scurrile', 'Linguaggio Scurrile'), ('Contenuti Violenti', 'Contenuti Violenti'), ('Contenuti non inerenti allo studio', 'Contenuti non inerenti allo studio'), ('Contenuti illeggibili', 'Contenuti illeggibili'), ('Materiale illecito/inadatto al contesto', 'Materiale illecito/inadatto al contesto'), ('Contenuto irriverente e di cattivo gusto', 'Contenuto irriverente e di cattivo gusto')], default='linguaggio scurrile', max_length=60),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni', to='content.Nota'),
        ),
    ]
