# Generated by Django 3.0.8 on 2020-11-03 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_auto_20201103_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='segnalanti',
            field=models.ManyToManyField(blank=True, related_name='note_segnalate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='segnalazioni', to='content.Nota'),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='segnalazioni', to=settings.AUTH_USER_MODEL),
        ),
    ]
